"""Create the requested explanatory notebook, reusing verified hurricane solves."""
from pathlib import Path
import copy,json,shutil,hashlib
import nbformat as nbf
from nbclient import NotebookClient
from jupyter_client import KernelManager
from jupyter_client.kernelspec import KernelSpecManager
root=Path(__file__).resolve().parents[1]
out=root/'output/hurricane_auxiliary_expanded'
shutil.copytree(root/'output/hurricane_cps_expanded',out,dirs_exist_ok=True)
old=root/'notebooks/legacy/1.analyze_CPS.ipynb';path=root/'notebooks/legacy/0.analyze_hurricans.ipynb'
nb=nbf.reads(old.read_text(encoding='utf-8').replace('output/hurricane_cps_expanded','output/hurricane_auxiliary_expanded'),4)
nb.cells[0].source += '''

**Auxiliary-point walkthrough:** this notebook adds exact point-generation records, a worked circle–segment calculation and full/zoomed views of both tracks in every selected pair. The three-method results are reused from the verified hurricane run on these identical inputs and settings (45 optimal results, three CPS-2F resource limits). Running all cells recomputes them. Auxiliary construction is evaluated even when the joint optimizer did not finish; certificate-based solutions need not construct the auxiliary graph in their actual execution.'''
heading=nbf.v4.new_markdown_cell(r'''### 3.1 How CPS-2F adds auxiliary points

For curve A, let $P=(p_0,\ldots,p_{m-1})$ and use radius $\delta_1$; repeat for B using $\delta_2$. **δ₃ does not generate auxiliary points**: it constrains the discrete coupling of A′ and B′.

1. Centre a circle of radius δ at **each original vertex** $c=p_j$.
2. Intersect its boundary with **every original segment** $p_i p_{i+1}$. In these planar data, the solver's spheres are circles.
3. Write $x(t)=p_i+t(p_{i+1}-p_i)$ and solve $\|x(t)-c\|^2=\delta^2$. With $v=p_{i+1}-p_i$, $q=p_i-c$:

   $$a=v\cdot v,\quad b=2q\cdot v,\quad c_0=q\cdot q-\delta^2,\qquad
   at^2+bt+c_0=0.$$

   There are at most two roots per circle–edge pair. The implementation uses an equivalent closest-point formula for numerical stability: $t_0=-q\cdot v/(v\cdot v)$, $s=\delta^2-\|q+t_0v\|^2$, then $t=t_0\pm\sqrt{s/(v\cdot v)}$ when the slack is nonnegative within tolerance.
4. Keep interior roots ($10^{-9}<t<1-10^{-9}$); the original endpoints already exist. Skip zero-length edges. Sort using the **curve parameter** $i+t$ and deduplicate within $10^{-10}$. Coincident spatial positions reached at different places along a looping curve retain different parameters.
5. Insert those positions into the original order to obtain $P^*$. **The geometry stays identical.** Auxiliary positions serve as owner positions in the CPS-2F configuration graph. Simplified output vertices are still selected from the original track, and CPS-3F and Independent GCS add no auxiliary points.

The bound $2m(m-1)$ counts at most two intersections for each of m circles and m−1 segments. Actual additions are usually fewer: many roots lie outside segments, some intersections are at existing vertices, and repeated parameter events are merged. The bound excludes originals; $|P^*|=m+\text{added auxiliary points}$.

Orange crosses below are added positions; blue open circles are original vertices. Purple rings highlight the intersections generated by one displayed circle. These are computational positions, not extra hurricane observations.''')
source1='''from hurricane_auxiliary import point_catalog, worked_intersection, auxiliary_curve_plots
from cps_paper_algorithms import extended_curve
construction_summary=point_catalog(data,parameters,OUT)
display(HTML(construction_summary.to_html(index=False,float_format=lambda x:f'{x:.3f}')))
print('Actual auxiliary generator used by the CPS-2F solver:')
print(inspect.getsource(extended_curve))'''
heading2=nbf.v4.new_markdown_cell('''### 3.2 Worked calculation on an actual hurricane edge

The table gives the quadratic coefficients, discriminant, accepted root, resulting coordinates, and distance back to the circle centre. Indices are zero-based. The left panel shows that edge and circle; the right panel shows where the root falls in the ordered curve parameter. All roots on the selected edge appear in the right panel, including those generated by other circles.''')
source2='''example_parameter=parameters.iloc[0]
example_item=data['instances'][example_parameter.pair+'@1']
worked=worked_intersection(example_item,example_parameter.delta1,OUT)
display(HTML(worked.to_html(index=False,float_format=lambda x:f'{x:.6g}')))
assert np.allclose(worked.distance_to_center_km,worked.radius_km,rtol=1e-9,atol=1e-7)'''
heading3=nbf.v4.new_markdown_cell('''### 3.3 Auxiliary points on both curves, for every selected pair

Each figure uses α=1: the top row shows **all original and added points** on A and B; the bottom row zooms into one generating circle per curve. The displayed circle is centred at the vertex generating the most accepted events. Other orange points inside the zoom can come from other circles. Point counts include the complete curves, not just the zoom. Some marks can overlap at this scale; the exported catalogue gives every position exactly.

Construction tables cover **both α=1 and α=2**. Set `alpha=2` below to show the second setting. Counts are computed even for optimizer resource limits, so they describe the graph construction for the configured instance, not a claim that every solver run materialized it.''')
source3='''auxiliary_curve_plots(data,parameters,OUT,alpha=ALPHAS[0])
display(Markdown('[All extended-curve points](output/hurricane_auxiliary/extended_curve_points.csv) · '
    '[Circle–edge root events](output/hurricane_auxiliary/auxiliary_intersection_events.csv) · '
    '[Construction counts](output/hurricane_auxiliary/auxiliary_construction_summary.csv)'))
auxiliary_manifest=dict(source='verified output/hurricane_cps results; same inputs and settings',
    plotted_alpha=ALPHAS[0],catalog_alphas=list(ALPHAS),curve_cases=len(construction_summary),
    sha256={name:hashlib.sha256((ROOT/name).read_bytes()).hexdigest() for name in
            ['src/hurricane_auxiliary.py','src/hurricane_cps.py','src/cps_paper_algorithms.py']})
(OUT/'auxiliary_manifest.json').write_text(json.dumps(auxiliary_manifest,indent=2))'''
newcells=[heading,nbf.v4.new_code_cell(source1),heading2,nbf.v4.new_code_cell(source2),heading3,nbf.v4.new_code_cell(source3)]
for cell in newcells:
    cell.source=cell.source.replace('output/hurricane_auxiliary/','output/hurricane_auxiliary_expanded/').replace('verified output/hurricane_cps results','verified output/hurricane_cps_expanded results')
nb.cells[0].source=nb.cells[0].source.replace('(45 optimal results, three CPS-2F resource limits)','(see the current status table)').replace('Running all cells recomputes them.','Running all cells reuses verified optimal results and retries unfinished cases.')
loading=next(c for c in nb.cells if c.cell_type=='code' and 'tracks, metadata, candidate_pairs=load_hurricanes' in c.source)
bootstrap=nbf.v4.new_code_cell("data,selected=organize(tracks,candidate_pairs,PAIRS_PER_BASIN)\nparameters=pd.read_csv(OUT/'parameters.csv')")
mini=nbf.v4.new_notebook(cells=[copy.deepcopy(loading),bootstrap]+copy.deepcopy(newcells))
km=KernelManager(kernel_name='protein-analysis',kernel_spec_manager=KernelSpecManager(kernel_dirs=[str(root/'.analysis_kernels')]))
def progress(cell,cell_index,**kwargs):print(f'Auxiliary reporting cell {cell_index+1}/{len(mini.cells)}',flush=True)
NotebookClient(mini,km=km,timeout=600,resources={'metadata':{'path':str(root)}},on_cell_start=progress).execute()
newcells=mini.cells[2:]
count=max(c.execution_count or 0 for c in nb.cells if c.cell_type=='code')
for c in newcells:
    if c.cell_type=='code':
        count+=1;c.execution_count=count
        c.metadata['execution_note']='Executed from identical loaded inputs and stored threshold table'
index=next(i for i,c in enumerate(nb.cells) if c.source.startswith('## 4.'))
nb.cells[index:index]=newcells
nbf.validate(nb);nbf.write(nb,path)
assert all(c.execution_count is not None and not any(o.output_type=='error' for o in c.outputs)
           for c in nb.cells if c.cell_type=='code')
print(f'Saved {path.name}: {len(nb.cells)} cells; all code cells have executed outputs.')
